spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
